source "https://rubygems.org"

gem "rack", "1.5.2"
gem "rake"
gem "sinatra"
gem "sinatra-contrib"
gem "rack-contrib"
gem "sinatra-cross_origin", "~> 0.3.1"
gem "songkick-oauth2-provider", git:"https://github.com/songkick/oauth2-provider"
gem "sinatra-activerecord"
gem "pg"
gem "active_model_serializers"
gem "protected_attributes"
gem "sentry-raven"
gem "slugify"
gem "opentok", "~> 2.2"
gem "bcrypt"
gem "rspec"
gem "database_cleaner"
gem "rspec_junit_formatter"